### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by am549** [Cireson/Community_AdvancedPortalSearch#1]
Have performs steps as documented but the options do not appear. Have restarted IIS, recycled app pool and website to no effect

**Comment by am549** [comment]
Have found the cause, the contents of the custom.js told to copy are incorrect. The loadscript commands don't match the names of the scripts copied to the search folder.

**Comment by scoussens** [comment]
@geoffross see above, does this need updated?

**Comment by geoffross** [comment]
Yes, fixed. Thanks for feedback @am549
