### ISSUE TITLE
Enter while searching

### ISSUE THREAD

**Issue by corbo-we** [Cireson/Community_AdvancedPortalSearch#2]
Pressing enter while searching takes you away from your search.  I get that we can say don't press enter, but you know users that use our stuff.  Can we do something like the following in InitSearch.js:

`
$(document).ready(function () {

	//Get a reference of the search input text box
	var searchInput = $("input[name=searchText]");

	//Add ID for css formating of the result list
	searchInput.attr('id', 'searchText');

	// Add Software Asset Search Type
	$(".navbar__search--dropdown ul").append('<li><a id="SoftwareAssetSearchType">Software Asset</a></li>');
	// Add Hardware Asset Search Type
	$(".navbar__search--dropdown ul").append('<li><a id="HardwareAssetSearchType">Hardware Asset</a></li>');
	// Add Hardware Asset Search Type
	$(".navbar__search--dropdown ul").append('<li><a id="UserSearchType">User</a></li>');

	//Add Custom toggle event handling
	$(".dropdown-menu").on("click", "li", function (event) {

		var searchType = event.target.id;
		//console.log(event);

		// If Autocomplete already exists destroy, just do clean everything up... IT Monkey would love it!!
		if (searchInput.data("kendoAutoComplete")) {
			customSearchLib.disableCustomHeaderSearch(searchInput);
		}

		function disableSearchKeys() {
			$("span.navbar__search--btn").hide();
			$("input[name=searchText]").unbind("keypress");
		}

		switch (searchType) {
			case "SoftwareAssetSearchType":
				customSearchSoftwareAsset.initSearch(searchInput);
				// Update Search Param and Concept
				var currentURL = window.location.href;
				var searchParam = $("input[name=search_param]"); //the hidden field which holds the search type id
				var searchConcept = $("span[id=search_concept]"); //the span field which displays the search type value      
				searchParam.val("SoftwareAsset");
				searchConcept.html('Software Asset');
				disableSearchKeys();
				break;
			case "HardwareAssetSearchType":
				customSearchHardwareAsset.initSearch(searchInput);
				// Update Search Param and Concept
				var currentURL = window.location.href;
				var searchParam = $("input[name=search_param]"); //the hidden field which holds the search type id
				var searchConcept = $("span[id=search_concept]"); //the span field which displays the search type value      
				searchParam.val("HardwareAsset");
				searchConcept.html('Hardware Asset');
				disableSearchKeys();
				break;
			case "UserSearchType":
				customSearchUser.initSearch(searchInput);
				// Update Search Param and Concept
				var currentURL = window.location.href;
				var searchParam = $("input[name=search_param]"); //the hidden field which holds the search type id
				var searchConcept = $("span[id=search_concept]"); //the span field which displays the search type value      
				searchParam.val("User");
				searchConcept.html('User');
				disableSearchKeys();
				break;
			default:
				$("span.navbar__search--btn").show();
				$("input[name=searchText]").keypress(function(event) {
                    if (event.keyCode == 13) {
                        app.headerSearchWorkItem();
                    }
                });
				break;
		}
	});

	if (typeof customSearchHardwareAsset == "undefined") {
		app.events.subscribe('customSearchHardwareAssetCreated', function () {
			init(searchInput)
		});
	}
	else {
		init(searchInput);
	}

	function init(searchInput) {
		if (session.user.AssetManager === 1) {
			customSearchHardwareAsset.initSearch(searchInput);
			// set Hardware Asset search as default if user is hardware asset manager
			//var currentURL = window.location.href;
			//var searchParam = $("input[name=search_param]"); //the hidden field which holds the search type id
			//var searchConcept = $("span[id=search_concept]"); //the span field which displays the search type value      
			//searchParam.val("HardwareAsset");
			//searchConcept.html('Hardware Asset');    

		}
	};
});`

**Comment by geoffross** [comment]
@corbo-we Yes, looks nice. We actually have a whole new version of this ready for v9 which should come soon which doesn't have a 'live' search as a lot of feedback has been negative around that - the Enter Key being one main area. In the mean time, I like this solution. Do you want to make a pull request, I'll test and merge.

**Comment by geoffross** [comment]
Thanks @corbo-we. Nice addition
